# Default title used in case no one is defined in page
title: "Massi-X, Your favorite developer!"

# My name for use throughout the site
author: "Massi-X"

# SASS settings
sass:
  style: compressed
  sourcemap: development

#URLs
cookie_domain: "massi-x.dev" #necessary for subdomains